Imports MySql.Data.MySqlClient

Public Class ListasDiversas
    Private dbMain As [Db] = New Db

    Public Function Escolaridades() As Array
        Dim escolar As New List(Of String)
        escolar.Add("Analfabeto")
        escolar.Add("Infantil Completo")
        escolar.Add("Infantil Incompleto")
        escolar.Add("Fundamental Completo")
        escolar.Add("Fundamental Incompleto")
        escolar.Add("Médio Completo")
        escolar.Add("Médio Incompleto")
        escolar.Add("Superior Completo")
        escolar.Add("Superior Incompleto")
        escolar.Add("Pós Completo")
        escolar.Add("Pós Incompleto")
        escolar.Add("Mestrado Completo")
        escolar.Add("Mestrado Incompleto")
        escolar.Add("Doutorado Completo")
        escolar.Add("Doutorado Incompleto")

        Return escolar.ToArray
    End Function

    Public Function FatorSanguineo() As Array
        Dim fator As New List(Of String)
        With fator
            .Add("A+")
            .Add("A-")
            .Add("B+")
            .Add("B-")
            .Add("AB+")
            .Add("AB-")
            .Add("O+")
            .Add("O-")
        End With
        Return fator.ToArray
    End Function

    Public Function SimNao() As Array
        Dim escolha As New List(Of String)
        With escolha
            .Add("Não")
            .Add("Sim")
        End With
        Return escolha.ToArray
    End Function

    Public Function Estados() As Array
        Dim uf As New List(Of String)
        With uf
            .Add("AC")
            .Add("AL")
            .Add("AP")
            .Add("AM")
            .Add("BA")
            .Add("CE")
            .Add("DF")
            .Add("ES")
            .Add("GO")
            .Add("MA")
            .Add("MT")
            .Add("MS")
            .Add("MG")
            .Add("PA")
            .Add("PB")
            .Add("PR")
            .Add("PE")
            .Add("PI")
            .Add("RJ")
            .Add("RN")
            .Add("RS")
            .Add("RO")
            .Add("RR")
            .Add("SC")
            .Add("SP")
            .Add("SE")
            .Add("TO")
        End With
        Return uf.ToArray
    End Function

    Public Function Municipios(Optional uf As String = "RJ") As Array
        Dim cid As New List(Of String)
        Select Case uf
            Case "RJ"
                With cid
                    .Add("Angra dos Reis")
                    .Add("Aperibé")
                    .Add("Araruama")
                    .Add("Areal")
                    .Add("Armação dos Búzios")
                    .Add("Arraial do Cabo")
                    .Add("Barra do Piraí")
                    .Add("Barra Mansa")
                    .Add("Belford Roxo")
                    .Add("Bom Jardim")
                    .Add("Bom Jesus do Itabapoana")
                    .Add("Cabo Frio")
                    .Add("Cachoeiras de Macacu")
                    .Add("Cambuci")
                    .Add("Campos dos Goytacazes")
                    .Add("Cantagalo")
                    .Add("Carapebus")
                    .Add("Cardoso Moreira")
                    .Add("Carmo")
                    .Add("Casimiro de Abreu")
                    .Add("Comendador Levy Gasparian")
                    .Add("Conceição de Macabu")
                    .Add("Cordeiro")
                    .Add("Duas Barras")
                    .Add("Duque de Caxias")
                    .Add("Engenheiro Paulo de Frontin")
                    .Add("Guapimirim")
                    .Add("Iguaba Grande")
                    .Add("Itaboraí")
                    .Add("Itaguaí")
                    .Add("Italva")
                    .Add("Itaocara")
                    .Add("Itaperuna")
                    .Add("Itatiaia")
                    .Add("Japeri")
                    .Add("Laje do Muriaé")
                    .Add("Macaé")
                    .Add("Macuco")
                    .Add("Magé")
                    .Add("Mangaratiba")
                    .Add("Maricá")
                    .Add("Mendes")
                    .Add("Mesquita")
                    .Add("Miguel Pereira")
                    .Add("Miracema")
                    .Add("Natividade")
                    .Add("Nilópolis")
                    .Add("Niterói")
                    .Add("Nova Friburgo")
                    .Add("Nova Iguaçu")
                    .Add("Paracambi")
                    .Add("Paraíba do Sul")
                    .Add("Paraty")
                    .Add("Paty do Alferes")
                    .Add("Petrópolis")
                    .Add("Pinheiral")
                    .Add("Piraí")
                    .Add("Porciûncula")
                    .Add("Porto Real")
                    .Add("Quatis")
                    .Add("Queimados")
                    .Add("Quissamã")
                    .Add("Resende")
                    .Add("Rio Bonito")
                    .Add("Rio Claro")
                    .Add("Rio das Flores")
                    .Add("Rio das Ostras")
                    .Add("Rio de Janeiro")
                    .Add("Santa Maria Madalena")
                    .Add("Santo Antônio de Pádua")
                    .Add("São Fidélis")
                    .Add("São Francisco de Itabapoana")
                    .Add("São Gonçalo")
                    .Add("São João da Barra")
                    .Add("São João de Meriti")
                    .Add("São José de Ubá")
                    .Add("São José do Vale do Rio Preto")
                    .Add("São Pedro da Aldeia")
                    .Add("São Sebastião do Alto")
                    .Add("Sapucaia")
                    .Add("Saquarema")
                    .Add("Seropédica")
                    .Add("Silva Jardim")
                    .Add("Sumidouro")
                    .Add("Tanguá")
                    .Add("Teresópolis")
                    .Add("Trajano de Moraes")
                    .Add("Três Rios")
                    .Add("Valença")
                    .Add("Varre-Sai")
                    .Add("Vassouras")
                    .Add("Volta Redonda")
                End With
            Case "SP"
                With cid
                    .Add("Adamantina")
                    .Add("Adolfo")
                    .Add("Aguaí")
                    .Add("Águas da Prata")
                    .Add("Águas de Lindóia")
                    .Add("Águas de Santa Bárbara")
                    .Add("Águas de São Pedro")
                    .Add("Agudos")
                    .Add("Alambari")
                    .Add("Alfredo Marcondes")
                    .Add("Altair")
                    .Add("Altinópolis")
                    .Add("Alto Alegre")
                    .Add("Alumínio")
                    .Add("Álvares Florence")
                    .Add("Álvares Machado")
                    .Add("Álvaro de Carvalho")
                    .Add("Alvinlândia")
                    .Add("Americana")
                    .Add("Américo Brasiliense")
                    .Add("Américo de Campos")
                    .Add("Amparo")
                    .Add("Analândia")
                    .Add("Andradina")
                    .Add("Angatuba")
                    .Add("Anhembi")
                    .Add("Anhumas")
                    .Add("Aparecida")
                    .Add("Aparecida d'Oeste")
                    .Add("Apiaí")
                    .Add("Araçariguama")
                    .Add("Araçatuba")
                    .Add("Araçoiaba da Serra")
                    .Add("Aramina")
                    .Add("Arandu")
                    .Add("Arapeí")
                    .Add("Araraquara")
                    .Add("Araras")
                    .Add("Arco-Íris")
                    .Add("Arealva")
                    .Add("Areias")
                    .Add("Areiópolis")
                    .Add("Ariranha")
                    .Add("Artur Nogueira")
                    .Add("Arujá")
                    .Add("Aspásia")
                    .Add("Assis")
                    .Add("Atibaia")
                    .Add("Auriflama")
                    .Add("Avaí")
                    .Add("Avanhandava")
                    .Add("Avaré")
                    .Add("Bady Bassitt")
                    .Add("Balbinos")
                    .Add("Bálsamo")
                    .Add("Bananal")
                    .Add("Barão de Antonina")
                    .Add("Barbosa")
                    .Add("Bariri")
                    .Add("Barra Bonita")
                    .Add("Barra do Chapéu")
                    .Add("Barra do Turvo")
                    .Add("Barretos")
                    .Add("Barrinha")
                    .Add("Barueri")
                    .Add("Bastos")
                    .Add("Batatais")
                    .Add("Bauru")
                    .Add("Bebedouro")
                    .Add("Bento de Abreu")
                    .Add("Bernardino de Campos")
                    .Add("Bertioga")
                    .Add("Bilac")
                    .Add("Birigui")
                    .Add("Biritiba Mirim")
                    .Add("Boa Esperança do Sul")
                    .Add("Bocaina")
                    .Add("Bofete")
                    .Add("Boituva")
                    .Add("Bom Jesus dos Perdões")
                    .Add("Bom Sucesso de Itararé")
                    .Add("Borá")
                    .Add("Boraceia")
                    .Add("Borborema")
                    .Add("Borebi")
                    .Add("Botucatu")
                    .Add("Bragança Paulista")
                    .Add("Braúna")
                    .Add("Brejo Alegre")
                    .Add("Brodowski")
                    .Add("Brotas")
                    .Add("Buri")
                    .Add("Buritama")
                    .Add("Buritizal")
                    .Add("Cabrália Paulista")
                    .Add("Cabreúva")
                    .Add("Caçapava")
                    .Add("Cachoeira Paulista")
                    .Add("Caconde")
                    .Add("Cafelândia")
                    .Add("Caiabu")
                    .Add("Caieiras")
                    .Add("Caiuá")
                    .Add("Cajamar")
                    .Add("Cajati")
                    .Add("Cajobi")
                    .Add("Cajuru")
                    .Add("Campina do Monte Alegre")
                    .Add("Campinas")
                    .Add("Campo Limpo Paulista")
                    .Add("Campos do Jordão")
                    .Add("Campos Novos Paulista")
                    .Add("Cananéia")
                    .Add("Canas")
                    .Add("Cândido Mota")
                    .Add("Cândido Rodrigues")
                    .Add("Canitar")
                    .Add("Capão Bonito")
                    .Add("Capela do Alto")
                    .Add("Capivari")
                    .Add("Caraguatatuba")
                    .Add("Carapicuíba")
                    .Add("Cardoso")
                    .Add("Casa Branca")
                    .Add("Cássia dos Coqueiros")
                    .Add("Castilho")
                    .Add("Catanduva")
                    .Add("Catiguá")
                    .Add("Cedral")
                    .Add("Cerqueira César")
                    .Add("Cerquilho")
                    .Add("Cesário Lange")
                    .Add("Charqueada")
                    .Add("Chavantes")
                    .Add("Clementina")
                    .Add("Colina")
                    .Add("Colômbia")
                    .Add("Conchal")
                    .Add("Conchas")
                    .Add("Cordeirópolis")
                    .Add("Coroados")
                    .Add("Coronel Macedo")
                    .Add("Corumbataí")
                    .Add("Cosmópolis")
                    .Add("Cosmorama")
                    .Add("Cotia")
                    .Add("Cravinhos")
                    .Add("Cristais Paulista")
                    .Add("Cruzália")
                    .Add("Cruzeiro")
                    .Add("Cubatão")
                    .Add("Cunha")
                    .Add("Descalvado")
                    .Add("Diadema")
                    .Add("Dirce Reis")
                    .Add("Divinolândia")
                    .Add("Dobrada")
                    .Add("Dois Córregos")
                    .Add("Dolcinópolis")
                    .Add("Dourado")
                    .Add("Dracena")
                    .Add("Duartina")
                    .Add("Dumont")
                    .Add("Echaporã")
                    .Add("Eldorado")
                    .Add("Elias Fausto")
                    .Add("Elisiário")
                    .Add("Embaúba")
                    .Add("Embu das Artes")
                    .Add("Embu-Guaçu")
                    .Add("Emilianópolis")
                    .Add("Engenheiro Coelho")
                    .Add("Espírito Santo do Pinhal")
                    .Add("Espírito Santo do Turvo")
                    .Add("Estiva Gerbi")
                    .Add("Estrela do Norte")
                    .Add("Estrela d'Oeste")
                    .Add("Euclides da Cunha Paulista")
                    .Add("Fartura")
                    .Add("Fernando Prestes")
                    .Add("Fernandópolis")
                    .Add("Fernão")
                    .Add("Ferraz de Vasconcelos")
                    .Add("Flora Rica")
                    .Add("Floreal")
                    .Add("Flórida Paulista")
                    .Add("Florínea")
                    .Add("Franca")
                    .Add("Francisco Morato")
                    .Add("Franco da Rocha")
                    .Add("Gabriel Monteiro")
                    .Add("Gália")
                    .Add("Garça")
                    .Add("Gastão Vidigal")
                    .Add("Gavião Peixoto")
                    .Add("General Salgado")
                    .Add("Getulina")
                    .Add("Glicério")
                    .Add("Guaiçara")
                    .Add("Guaimbê")
                    .Add("Guaíra")
                    .Add("Guapiaçu")
                    .Add("Guapiara")
                    .Add("Guará")
                    .Add("Guaraçaí")
                    .Add("Guaraci")
                    .Add("Guarani d'Oeste")
                    .Add("Guarantã")
                    .Add("Guararapes")
                    .Add("Guararema")
                    .Add("Guaratinguetá")
                    .Add("Guareí")
                    .Add("Guariba")
                    .Add("Guarujá")
                    .Add("Guarulhos")
                    .Add("Guatapará")
                    .Add("Guzolândia")
                    .Add("Herculândia")
                    .Add("Holambra")
                    .Add("Hortolândia")
                    .Add("Iacanga")
                    .Add("Iacri")
                    .Add("Iaras")
                    .Add("Ibaté")
                    .Add("Ibirá")
                    .Add("Ibirarema")
                    .Add("Ibitinga")
                    .Add("Ibiúna")
                    .Add("Icém")
                    .Add("Iepê")
                    .Add("Igaraçu do Tietê")
                    .Add("Igarapava")
                    .Add("Igaratá")
                    .Add("Iguape")
                    .Add("Ilha Comprida")
                    .Add("Ilha Solteira")
                    .Add("Ilhabela")
                    .Add("Indaiatuba")
                    .Add("Indiana")
                    .Add("Indiaporã")
                    .Add("Inúbia Paulista")
                    .Add("Ipaussu")
                    .Add("Iperó")
                    .Add("Ipeúna")
                    .Add("Ipiguá")
                    .Add("Iporanga")
                    .Add("Ipuã")
                    .Add("Iracemápolis")
                    .Add("Irapuã")
                    .Add("Irapuru")
                    .Add("Itaberá")
                    .Add("Itaí")
                    .Add("Itajobi")
                    .Add("Itaju")
                    .Add("Itanhaém")
                    .Add("Itaoca")
                    .Add("Itapecerica da Serra")
                    .Add("Itapetininga")
                    .Add("Itapeva")
                    .Add("Itapevi")
                    .Add("Itapira")
                    .Add("Itapirapuã Paulista")
                    .Add("Itápolis")
                    .Add("Itaporanga")
                    .Add("Itapuí")
                    .Add("Itapura")
                    .Add("Itaquaquecetuba")
                    .Add("Itararé")
                    .Add("Itariri")
                    .Add("Itatiba")
                    .Add("Itatinga")
                    .Add("Itirapina")
                    .Add("Itirapuã")
                    .Add("Itobi")
                    .Add("Itu")
                    .Add("Itupeva")
                    .Add("Ituverava")
                    .Add("Jaborandi")
                    .Add("Jaboticabal")
                    .Add("Jacareí")
                    .Add("Jaci")
                    .Add("Jacupiranga")
                    .Add("Jaguariúna")
                    .Add("Jales")
                    .Add("Jambeiro")
                    .Add("Jandira")
                    .Add("Jardinópolis")
                    .Add("Jarinu")
                    .Add("Jaú")
                    .Add("Jeriquara")
                    .Add("Joanópolis")
                    .Add("João Ramalho")
                    .Add("José Bonifácio")
                    .Add("Júlio Mesquita")
                    .Add("Jumirim")
                    .Add("Jundiaí")
                    .Add("Junqueirópolis")
                    .Add("Juquiá")
                    .Add("Juquitiba")
                    .Add("Lagoinha")
                    .Add("Laranjal Paulista")
                    .Add("Lavínia")
                    .Add("Lavrinhas")
                    .Add("Leme")
                    .Add("Lençóis Paulista")
                    .Add("Limeira")
                    .Add("Lindóia")
                    .Add("Lins")
                    .Add("Lorena")
                    .Add("Lourdes")
                    .Add("LouveiraLouveira")
                    .Add("Lucélia")
                    .Add("Lucianópolis")
                    .Add("Luiz Antônio")
                    .Add("Luiziânia")
                    .Add("Lupércio")
                    .Add("Lutécia")
                    .Add("Macatuba")
                    .Add("Macaubal")
                    .Add("Macedônia")
                    .Add("Magda")
                    .Add("Mairinque")
                    .Add("Mairiporã")
                    .Add("Manduri")
                    .Add("Marabá Paulista")
                    .Add("Maracaí")
                    .Add("Marapoama")
                    .Add("Mariápolis")
                    .Add("Marília")
                    .Add("Marinópolis")
                    .Add("Martinópolis")
                    .Add("Matão")
                    .Add("Mauá")
                    .Add("Mendonça")
                    .Add("Meridiano")
                    .Add("Mesópolis")
                    .Add("Miguelópolis")
                    .Add("Mineiros do Tietê")
                    .Add("Mira Estrela")
                    .Add("Miracatu")
                    .Add("Mirandópolis")
                    .Add("Mirante do Paranapanema")
                    .Add("Mirassol")
                    .Add("Mirassolândia")
                    .Add("Mococa")
                    .Add("Mogi das Cruzes")
                    .Add("Mogi Guaçu")
                    .Add("Mogi Mirim")
                    .Add("Mombuca")
                    .Add("Monções")
                    .Add("Mongaguá")
                    .Add("Monte Alegre do Sul")
                    .Add("Monte Alto")
                    .Add("Monte Aprazível")
                    .Add("Monte Azul Paulista")
                    .Add("Monte Castelo")
                    .Add("Monte Mor")
                    .Add("Monteiro Lobato")
                    .Add("Morro Agudo")
                    .Add("Morungaba")
                    .Add("Motuca")
                    .Add("Murutinga do Sul")
                    .Add("Nantes")
                    .Add("Narandiba")
                    .Add("Natividade da Serra")
                    .Add("Nazaré Paulista")
                    .Add("Neves Paulista")
                    .Add("Nhandeara")
                    .Add("Nipoã")
                    .Add("Nova Aliança")
                    .Add("Nova Campina")
                    .Add("Nova Canaã Paulista")
                    .Add("Nova Castilho")
                    .Add("Nova Europa")
                    .Add("Nova Granada")
                    .Add("Nova Guataporanga")
                    .Add("Nova Independência")
                    .Add("Nova Luzitânia")
                    .Add("Nova Odessa")
                    .Add("Novais")
                    .Add("Novo Horizonte")
                    .Add("Nuporanga")
                    .Add("Ocauçu")
                    .Add("Óleo")
                    .Add("Olímpia")
                    .Add("Onda Verde")
                    .Add("Oriente")
                    .Add("Orindiúva")
                    .Add("Orlândia")
                    .Add("Osasco")
                    .Add("Oscar Bressane")
                    .Add("Osvaldo Cruz")
                    .Add("Ourinhos")
                    .Add("Ouro Verde")
                    .Add("Ouroeste")
                    .Add("Pacaembu")
                    .Add("Palestina")
                    .Add("Palmares Paulista")
                    .Add("Palmeira d'Oeste")
                    .Add("Palmital")
                    .Add("Panorama")
                    .Add("Paraguaçu Paulista")
                    .Add("ParaibunaParaibuna")
                    .Add("Paraíso")
                    .Add("Paranapanema")
                    .Add("Paranapuã")
                    .Add("Parapuã")
                    .Add("Pardinho")
                    .Add("Pariquera-Açu")
                    .Add("Parisi")
                    .Add("Patrocínio Paulista")
                    .Add("Paulicéia")
                    .Add("Paulínia")
                    .Add("Paulistânia")
                    .Add("Paulo de Faria")
                    .Add("Pederneiras")
                    .Add("Pedra Bela")
                    .Add("Pedranópolis")
                    .Add("Pedregulho")
                    .Add("Pedreira")
                    .Add("Pedrinhas Paulista")
                    .Add("Pedro de Toledo")
                    .Add("Penápolis")
                    .Add("Pereira Barreto")
                    .Add("Pereiras")
                    .Add("Peruíbe")
                    .Add("Piacatu")
                    .Add("Piedade")
                    .Add("Pilar do Sul")
                    .Add("Pindamonhangaba")
                    .Add("Pindorama")
                    .Add("Pinhalzinho")
                    .Add("Piquerobi")
                    .Add("Piquete")
                    .Add("Piracaia")
                    .Add("Piracicaba")
                    .Add("Piraju")
                    .Add("Pirajuí")
                    .Add("Pirangi")
                    .Add("Pirapora do Bom Jesus")
                    .Add("Pirapozinho")
                    .Add("Pirassununga")
                    .Add("Piratininga")
                    .Add("Pitangueiras")
                    .Add("Planalto")
                    .Add("Platina")
                    .Add("Poá")
                    .Add("Poloni")
                    .Add("Pompeia")
                    .Add("Pongaí")
                    .Add("Pontal")
                    .Add("Pontalinda")
                    .Add("Pontes Gestal")
                    .Add("Populina")
                    .Add("Porangaba")
                    .Add("Porto Feliz")
                    .Add("Porto Ferreira")
                    .Add("Potim")
                    .Add("Potirendaba")
                    .Add("Pracinha")
                    .Add("Pradópolis")
                    .Add("Praia Grande")
                    .Add("Pratânia")
                    .Add("Presidente Alves")
                    .Add("Presidente Bernardes")
                    .Add("Presidente Epitácio")
                    .Add("Presidente Prudente")
                    .Add("Presidente Venceslau")
                    .Add("Promissão")
                    .Add("Quadra")
                    .Add("Quatá")
                    .Add("Queiroz")
                    .Add("Queluz")
                    .Add("Quintana")
                    .Add("Rafard")
                    .Add("Rancharia")
                    .Add("Redenção da Serra")
                    .Add("Regente Feijó")
                    .Add("Reginópolis")
                    .Add("Registro")
                    .Add("Restinga")
                    .Add("Ribeira")
                    .Add("Ribeirão Bonito")
                    .Add("Ribeirão Branco")
                    .Add("Ribeirão Corrente")
                    .Add("Ribeirão do Sul")
                    .Add("Ribeirão dos Índios")
                    .Add("Ribeirão Grande")
                    .Add("Ribeirão Pires")
                    .Add("Ribeirão Preto")
                    .Add("Rifaina")
                    .Add("Rincão")
                    .Add("Rinópolis")
                    .Add("Rio Claro")
                    .Add("Rio das Pedras")
                    .Add("Rio Grande da Serra")
                    .Add("Riolândia")
                    .Add("Riversul")
                    .Add("Rosana")
                    .Add("Roseira")
                    .Add("Rubiácea")
                    .Add("Rubineia")
                    .Add("Sabino")
                    .Add("Sagres")
                    .Add("Sales")
                    .Add("Sales Oliveira")
                    .Add("Salesópolis")
                    .Add("Salmourão")
                    .Add("Saltinho")
                    .Add("Salto")
                    .Add("Salto de Pirapora")
                    .Add("Salto Grande")
                    .Add("Sandovalina")
                    .Add("Santa Adélia")
                    .Add("Santa Albertina")
                    .Add("Santa Bárbara d'Oeste")
                    .Add("Santa Branca")
                    .Add("Santa Clara d'Oeste")
                    .Add("Santa Cruz da Conceição")
                    .Add("Santa Cruz da Esperança")
                    .Add("Santa Cruz das Palmeiras")
                    .Add("Santa Cruz do Rio Pardo")
                    .Add("Santa Ernestina")
                    .Add("Santa Fé do Sul")
                    .Add("Santa Gertrudes")
                    .Add("Santa Isabel")
                    .Add("Santa Lúcia")
                    .Add("Santa Maria da Serra")
                    .Add("Santa Mercedes")
                    .Add("Santa Rita do Passa Quatro")
                    .Add("Santa Rita d'Oeste")
                    .Add("Santa Rosa de Viterbo")
                    .Add("Santa Salete")
                    .Add("Santana da Ponte Pensa")
                    .Add("Santana de Parnaíba")
                    .Add("Santo Anastácio")
                    .Add("Santo André")
                    .Add("Santo Antônio da Alegria")
                    .Add("Santo Antônio de Posse")
                    .Add("Santo Antônio do Aracanguá")
                    .Add("Santo Antônio do Jardim")
                    .Add("Santo Antônio do Pinhal")
                    .Add("Santo Expedito")
                    .Add("Santópolis do Aguapeí")
                    .Add("Santos")
                    .Add("São Bento do Sapucaí")
                    .Add("São Bernardo do Campo")
                    .Add("São Caetano do Sul")
                    .Add("São Carlos")
                    .Add("São Francisco")
                    .Add("São João da Boa Vista")
                    .Add("São João das Duas Pontes")
                    .Add("São João de Iracema")
                    .Add("São João do Pau-d'Alho")
                    .Add("São Joaquim da Barra")
                    .Add("São José da Bela Vista")
                    .Add("São José do Barreiro")
                    .Add("São José do Rio Pardo")
                    .Add("São José do Rio Preto")
                    .Add("São José dos Campos")
                    .Add("São Lourenço da Serra")
                    .Add("São Luiz do Paraitinga")
                    .Add("São Manuel")
                    .Add("São Miguel Arcanjo")
                    .Add("São Paulo")
                    .Add("São Pedro")
                    .Add("São Pedro do Turvo")
                    .Add("São Roque")
                    .Add("São Sebastião")
                    .Add("São Sebastião da Grama")
                    .Add("São Simão")
                    .Add("São Vicente")
                    .Add("Sarapuí")
                    .Add("Sarutaiá")
                    .Add("Sebastianópolis do Sul")
                    .Add("Serra Azul")
                    .Add("Serra Negra")
                    .Add("Serrana")
                    .Add("Sertãozinho")
                    .Add("Sete Barras")
                    .Add("Severínia")
                    .Add("Silveiras")
                    .Add("Socorro")
                    .Add("Sorocaba")
                    .Add("Sud Mennucci")
                    .Add("Sumaré")
                    .Add("Suzanápolis")
                    .Add("Suzano")
                    .Add("Tabapuã")
                    .Add("Tabatinga")
                    .Add("Taboão da Serra")
                    .Add("Taciba")
                    .Add("Taguaí")
                    .Add("Taiaçu")
                    .Add("Taiuva")
                    .Add("Tambaú")
                    .Add("Tanabi")
                    .Add("Tapiraí")
                    .Add("Tapiratiba")
                    .Add("Taquaral")
                    .Add("Taquaritinga")
                    .Add("Taquarituba")
                    .Add("Taquarivaí")
                    .Add("Tarabai")
                    .Add("Tarumã")
                    .Add("Tatuí")
                    .Add("Taubaté")
                    .Add("Tejupá")
                    .Add("Teodoro Sampaio")
                    .Add("Terra Roxa")
                    .Add("Tietê")
                    .Add("Timburi")
                    .Add("Torre de Pedra")
                    .Add("Torrinha")
                    .Add("Trabiju")
                    .Add("Tremembé")
                    .Add("Três Fronteiras")
                    .Add("Tuiuti")
                    .Add("Tupã")
                    .Add("Tupi Paulista")
                    .Add("Turiúba")
                    .Add("Turmalina")
                    .Add("Ubarana")
                    .Add("Ubatuba")
                    .Add("Ubirajara")
                    .Add("Uchoa")
                    .Add("União Paulista")
                    .Add("Urânia")
                    .Add("Uru")
                    .Add("Urupês")
                    .Add("Valentim Gentil")
                    .Add("Valinhos")
                    .Add("Valparaíso")
                    .Add("Vargem")
                    .Add("Vargem Grande do Sul")
                    .Add("Vargem Grande Paulista")
                    .Add("Várzea Paulista")
                    .Add("Vera Cruz")
                    .Add("Vinhedo")
                    .Add("Viradouro")
                    .Add("Vista Alegre do Alto")
                    .Add("Vitória Brasil")
                    .Add("Votorantim")
                    .Add("Votuporanga")
                    .Add("Zacarias")
                End With
        End Select
        Return cid.ToArray
    End Function

    Public Function Cargos() As Array
        Dim cargo As New List(Of Object())
        With cargo
            .Add({0, "Administrador"})
            .Add({1, "Gerente"})
            .Add({2, "Caixa"})
            .Add({3, "Operador"})
            .Add({4, "Professor"})
            .Add({5, "Outros"})
        End With
        Return cargo.ToArray
    End Function

    Public Function Pendencias() As Array
        Dim sql As String = "SELECT pendencia FROM `pendencias` ORDER BY pendencia;"
        Dim conn As MySqlConnection = dbMain.OpenDB(Globais.unidade, Globais.user, Globais.pwd, Globais.databaseName)
        Dim vrs As MySqlDataReader = dbMain.OpenTable(conn, sql)

        Dim lista As New List(Of String)
        If vrs.HasRows Then
            Try
                While vrs.Read
                    With lista
                        .Add(vrs.GetString("pendencia"))
                    End With
                End While
            Catch ex As Exception
            End Try
        End If
        dbMain.CloseAll(conn, vrs)
        Return lista.ToArray
    End Function

    Public Function Cursos() As Array
        Dim curso As New ArrayList
        With curso
            .Add("Infantil")
            .Add("Fundamental")
            .Add("Médio")
            '.Add("Superior")
            '.Add("Pós")
            '.Add("Mestrado")
        End With

        Return curso.ToArray
    End Function

    Public Function Series(idCurso As Integer) As Array
        Dim _series As Object()() = {
            ({"Creche", "Maternal", "1º Período", "2º Período", "3º Período"}),
            ({"1º Ano", "2º Ano", "3º Ano", "4º Ano", "5º Ano", "6º Ano", "7º Ano", "8º Ano", "9º Ano"}),
            ({"1º Ano", "2º Ano", "3º Ano", "4º Ano"})
        }
        '.Add({3, "1º Semestre"})
        '.Add({3, "2º Semestre"})

        Dim serie As Object()
        If idCurso > -1 Then
            serie = _series(idCurso)
        End If

        Return serie
    End Function

    Public Function Turnos() As Array
        Dim turno As New ArrayList
        With turno
            .Add("Manhã")
            .Add("Tarde")
            .Add("Noite")
            .Add("Integral")
            .Add("Meio Período")
        End With

        Return turno.ToArray
    End Function

End Class

'// Busca Avançada 'match'
'//
'     Private match As DataGridViewCell()
'     match = (From row As DataGridViewRow In Me.DataGridViewPrecos.Rows From cell As DataGridViewCell In row.Cells Select cell Where CStr(cell.FormattedValue).Contains(Me.txbLocalizar.Text.ToUpper.Trim)).ToArray()
'     DataGridViewPrecos.Rows(match(pos).RowIndex).Selected = True
'     DataGridViewPrecos.FirstDisplayedScrollingRowIndex = match(pos).RowIndex
